### PR TITLE
doc: add a missing space in instructions (quick start)

### PR DESCRIPTION
**Pull request by ThibaudDauce**
I think this is the best pull request ever ^^

### CODE REVIEW

**Comment by andrewthad** [comment]
Thanks for fixing this.

**Comment by snoyberg** [comment]
Agreed, that was a bad typo on my part. Thanks :)

**Comment by ThibaudDauce** [comment]
By the way, one question, do we need to run  `stack install yesod-bin-1.4.11` anywhere or in the yesod directory?

**Comment by snoyberg** [comment]
Anywhere. The `yesod` directory doesn't exist at that point in the instructions.

**Comment by ThibaudDauce** [comment]
Yeah that's what I was thinking.
Thanks.

**Pull request merged**
